version: '3.7'
services:
  db:
    image: postgres:15-alpine
    env_file:
      - ./env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "python -m main"
    env_file:
      - ./env
    restart: always
    depends_on:
      - db



volumes:
  pgdata: